# Generated by Django 5.0.6 on 2024-07-15 20:37

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_Blog", "0005_alter_post_publish"),
    ]

    operations = [TrigramExtension()]
